"""Create da tabela tb_move

Revision ID: 4364facd4a7f
Revises: ce9530214121
Create Date: 2024-06-18 17:01:34.832725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4364facd4a7f'
down_revision: Union[str, None] = 'ce9530214121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_move',
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('move_name', sa.String(length=20), nullable=False),
    sa.Column('move_type', sa.Integer(), nullable=True),
    sa.Column('move_category', sa.Integer(), nullable=True),
    sa.Column('move_power', sa.Integer(), nullable=True),
    sa.Column('move_accuracy', sa.Integer(), nullable=True),
    sa.Column('move_basePP', sa.Integer(), nullable=True),
    sa.Column('move_description', sa.String(length=100), nullable=False),
    sa.Column('move_effect', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('move_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_move')
    # ### end Alembic commands ###
