"""Inclusao da tabela tb_learnByLevelUp

Revision ID: 84f1aa725184
Revises: 1fc88262abf3
Create Date: 2024-06-19 15:28:15.648428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f1aa725184'
down_revision: Union[str, None] = '1fc88262abf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_learnByLevelUp',
    sa.Column('LBLU_id', sa.Integer(), nullable=False),
    sa.Column('LBLU_pokemon', sa.Integer(), nullable=True),
    sa.Column('LBLU_move', sa.Integer(), nullable=True),
    sa.Column('LBLU_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('LBLU_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_learnByLevelUp')
    # ### end Alembic commands ###
