"""Tabela vantagens de tipo

Revision ID: b20151ecad4d
Revises: dab75bcc1323
Create Date: 2024-06-14 17:17:06.671790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20151ecad4d'
down_revision: Union[str, None] = 'dab75bcc1323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_combatAdvantage',
    sa.Column('cmAd_id', sa.Integer(), nullable=False),
    sa.Column('cmAd_name', sa.String(length=20), nullable=False),
    sa.Column('cmAd_multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('cmAd_id')
    )
    op.create_table('tb_typeAdvantage',
    sa.Column('tyAd_id', sa.Integer(), nullable=False),
    sa.Column('tyAd_attackType', sa.Integer(), nullable=True),
    sa.Column('tyAd_defenseType', sa.Integer(), nullable=True),
    sa.Column('tyAd_typeAdvantage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tyAd_id')
    )
    op.alter_column('tb_pokemon', 'poke_primaryType',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tb_pokemon', 'poke_secondaryType',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'tb_pokemon', 'tb_type', ['poke_secondaryType'], ['type_id'])
    op.create_foreign_key(None, 'tb_pokemon', 'tb_type', ['poke_primaryType'], ['type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_pokemon', type_='foreignkey')
    op.drop_constraint(None, 'tb_pokemon', type_='foreignkey')
    op.alter_column('tb_pokemon', 'poke_secondaryType',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tb_pokemon', 'poke_primaryType',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('tb_typeAdvantage')
    op.drop_table('tb_combatAdvantage')
    # ### end Alembic commands ###
