"""Inclusão da tabela de Status do pokemon

Revision ID: cb1ef4e0504d
Revises: fb4aa71c3a8d
Create Date: 2024-06-18 15:34:58.184096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'cb1ef4e0504d'
down_revision: Union[str, None] = 'fb4aa71c3a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    if 'tb_status' not in inspector.get_table_names():
        op.create_table(
            'tb_status',
            sa.Column('stat_id', sa.Integer(), nullable=False),
            sa.Column('stat_hp', sa.Integer(), nullable=False),
            sa.Column('stat_attack', sa.Integer(), nullable=False),
            sa.Column('stat_defense', sa.Integer(), nullable=False),
            sa.Column('stat_spAttack', sa.Integer(), nullable=False),
            sa.Column('stat_spDefense', sa.Integer(), nullable=False),
            sa.Column('stat_speed', sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint('stat_id')
        )

    columns_tb_pokemon = [col['name'] for col in inspector.get_columns('tb_pokemon')]
    with op.batch_alter_table('tb_pokemon', schema=None) as batch_op:
        if 'poke_baseStats' not in columns_tb_pokemon:
            batch_op.add_column(sa.Column('poke_baseStats', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_tb_pokemon_stats', 'tb_status', ['poke_baseStats'], ['stat_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_pokemon', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tb_pokemon_stats', type_='foreignkey')
        batch_op.drop_column('poke_baseStats')

    op.drop_table('tb_status')
    # ### end Alembic commands ###
