"""Relacionando tb_ability com tb_pokemon

Revision ID: ce9530214121
Revises: ee94f7828644
Create Date: 2024-06-18 15:57:48.928878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9530214121'
down_revision: Union[str, None] = 'ee94f7828644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_primaryAbility', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poke_secondaryAbility', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poke_hiddenAbility', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_primaryAbility', 'tb_ability', ['poke_primaryAbility'], ['ablt_id'])
        batch_op.create_foreign_key('fk_secondaryAbility', 'tb_ability', ['poke_secondaryAbility'], ['ablt_id'])
        batch_op.create_foreign_key('fk_hiddenAbility', 'tb_ability', ['poke_hiddenAbility'], ['ablt_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poke_hiddenAbility')
        batch_op.drop_column('poke_secondaryAbility')
        batch_op.drop_column('poke_primaryAbility')

    # ### end Alembic commands ###
