"""Tabela TbType criada

Revision ID: dab75bcc1323
Revises: 57395a8d1f91
Create Date: 2024-06-14 16:45:00.444259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab75bcc1323'
down_revision: Union[str, None] = '57395a8d1f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=20), nullable=False),
    sa.Column('type_picture', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.add_column('tb_pokemon', sa.Column('poke_primaryType', sa.Integer(), nullable=False))
    op.add_column('tb_pokemon', sa.Column('poke_secondaryType', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_pokemon', 'poke_secondaryType')
    op.drop_column('tb_pokemon', 'poke_primaryType')
    op.drop_table('tb_type')
    # ### end Alembic commands ###
