"""Colocando Foreign Keys

Revision ID: fb4aa71c3a8d
Revises: 57395a8d1f91
Create Date: 2024-06-17 15:23:58.867691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'fb4aa71c3a8d'
down_revision: Union[str, None] = '57395a8d1f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    if 'tb_type' not in inspector.get_table_names():
        op.create_table(
            'tb_type',
            sa.Column('type_id', sa.Integer, primary_key=True, nullable=False),
            sa.Column('type_name', sa.String(length=20), nullable=False),
            sa.Column('type_picture', sa.String(length=10), nullable=False)
        )

    with op.batch_alter_table('tb_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_primaryType', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poke_secondaryType', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tb_pokemon_primaryType', 'tb_type', ['poke_primaryType'], ['type_id'])
        batch_op.create_foreign_key('fk_tb_pokemon_secondaryType', 'tb_type', ['poke_secondaryType'], ['type_id'])

    with op.batch_alter_table('tb_typeAdvantage', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tb_typeAdvantage_combatAdvantage', 'tb_combatAdvantage', ['tyAd_typeAdvantage'], ['cmAd_id'])
        batch_op.create_foreign_key('fk_tb_typeAdvantage_attackType', 'tb_type', ['tyAd_attackType'], ['type_id'])
        batch_op.create_foreign_key('fk_tb_typeAdvantage_defenseType', 'tb_type', ['tyAd_defenseType'], ['type_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_typeAdvantage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tb_typeAdvantage_combatAdvantage', type_='foreignkey')
        batch_op.drop_constraint('fk_tb_typeAdvantage_attackType', type_='foreignkey')
        batch_op.drop_constraint('fk_tb_typeAdvantage_defenseType', type_='foreignkey')

    with op.batch_alter_table('tb_pokemon', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tb_pokemon_primaryType', type_='foreignkey')
        batch_op.drop_constraint('fk_tb_pokemon_secondaryType', type_='foreignkey')
        batch_op.drop_column('poke_secondaryType')
        batch_op.drop_column('poke_primaryType')

    op.drop_table('tb_type')
    # ### end Alembic commands ###
